fabric-1.19:
  required_when_enabled: true
  update_files:
    - lib/cloth_config.jar
  resource_paths:
    block_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/block'
    item_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/item'
    effect_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/effect'
    environment_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/environment'
    gui_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/gui'
    font_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/font'
    map_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/map'
    misc_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/misc'
    mob_effect_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/mob_effect'
    models_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/models'
    painting_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/painting'
    particle_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/particle'
    trims_textures_dir: 'lib/cloth_config.jar!/assets/cloth_config/textures/trims'
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }

    
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814064')
    }
name: "Culinary Construct"
