neoforge-1.21.4:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5987045')
    }
forge-1.21.3:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5987043')
    }
forge-1.21.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5987043')
    }
fabric-1.21.4:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:cloth-config-348521:5987042')
    }
neoforge-1.21.3:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5986999')
    }
neoforge-1.21.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5986999')
    }
fabric-1.21.3:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:cloth-config-348521:5986997')
    }
fabric-1.21.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:cloth-config-348521:5986997')
    }
neoforge-1.20.3:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729139')
    }
neoforge-1.20.4:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729139')
    }
forge-1.20.3:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729138')
    }
forge-1.20.4:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729138')
    }
fabric-1.20.3:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:cloth-config-348521:5729136')
    }
fabric-1.20.4:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:cloth-config-348521:5729136')
    }
neoforge-1.21:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729127')
    }
neoforge-1.21.1:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729127')
    }
forge-1.21:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729126')
    }
forge-1.21.1:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729126')
    }
fabric-1.21:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:cloth-config-348521:5729125')
    }
fabric-1.21.1:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:cloth-config-348521:5729125')
    }
neoforge-1.20.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729121')
    }
forge-1.20.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729120')
    }
fabric-1.20.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:cloth-config-348521:5729119')
    }
neoforge-1.20.5:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729118')
    }
neoforge-1.20.6:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:cloth-config-348521:5729118')
    }
name: "Cloth Config API"
