---
neoforge-1.21.5:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:6351757'
    }
  update_files:
    - ~
fabric-1.21.5:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:6351756'
    }
  update_files:
    - ~
neoforge-1.21.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5987045'
    }
  update_files:
    - ~
forge-1.21.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    minecraft {
        runs {
            client {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            server {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            data {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5987043')
    }
  update_files:
    - ~
forge-1.21.2:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    minecraft {
        runs {
            client {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            server {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            data {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5987043')
    }
  update_files:
    - ~
fabric-1.21.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5987042'
    }
  update_files:
    - ~
neoforge-1.21.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5986999'
    }
  update_files:
    - ~
neoforge-1.21.2:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5986999'
    }
  update_files:
    - ~
fabric-1.21.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5986997'
    }
  update_files:
    - ~
fabric-1.21.2:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5986997'
    }
  update_files:
    - ~
neoforge-1.20.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729139'
    }
  update_files:
    - ~
neoforge-1.20.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729139'
    }
  update_files:
    - ~
forge-1.20.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    minecraft {
        runs {
            client {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            server {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            data {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5729138')
    }
  update_files:
    - ~
forge-1.20.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    minecraft {
        runs {
            client {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            server {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            data {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5729138')
    }
  update_files:
    - ~
fabric-1.20.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5729136'
    }
  update_files:
    - ~
fabric-1.20.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5729136'
    }
  update_files:
    - ~
neoforge-1.21:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729127'
    }
  update_files:
    - ~
neoforge-1.21.1:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729127'
    }
  update_files:
    - ~
forge-1.21:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    minecraft {
        runs {
            client {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            server {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            data {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5729126')
    }
  update_files:
    - ~
forge-1.21.1:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    minecraft {
        runs {
            client {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            server {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            data {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5729126')
    }
  update_files:
    - ~
fabric-1.21:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5729125'
    }
  update_files:
    - ~
fabric-1.21.1:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5729125'
    }
  update_files:
    - ~
neoforge-1.20.2:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729121'
    }
  update_files:
    - ~
forge-1.20.2:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    minecraft {
        runs {
            client {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            server {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
            data {
                property 'mixin.env.remapRefMap', 'true'
                property 'mixin.env.refMapRemappingFile', '${projectDir}/build/createSrgToMcp/output.srg'
            }
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5729120')
    }
  update_files:
    - ~
name: "Cloth Config API"
