---
neoforge-1.21.8:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:6669837'
    }
  update_files:
    - ~
neoforge-1.21.7:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:6669837'
    }
  update_files:
    - ~
neoforge-1.21.6:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:6669837'
    }
  update_files:
    - ~
fabric-1.21.8:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:6669836'
    }
  update_files:
    - ~
fabric-1.21.7:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:6669836'
    }
  update_files:
    - ~
fabric-1.21.6:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:6669836'
    }
  update_files:
    - ~
neoforge-1.21.5:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:6351757'
    }
  update_files:
    - ~
fabric-1.21.5:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:6351756'
    }
  update_files:
    - ~
neoforge-1.21.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5987045'
    }
  update_files:
    - ~
forge-1.21.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5987043')
    }
  update_files:
    - ~
forge-1.21.2:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5987043')
    }
  update_files:
    - ~
fabric-1.21.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5987042'
    }
  update_files:
    - ~
neoforge-1.21.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5986999'
    }
  update_files:
    - ~
neoforge-1.21.2:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5986999'
    }
  update_files:
    - ~
fabric-1.21.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5986997'
    }
  update_files:
    - ~
fabric-1.21.2:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5986997'
    }
  update_files:
    - ~
neoforge-1.20.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729139'
    }
  update_files:
    - ~
neoforge-1.20.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729139'
    }
  update_files:
    - ~
forge-1.20.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5729138')
    }
  update_files:
    - ~
forge-1.20.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation fg.deobf('curse.maven:cloth-config-348521:5729138')
    }
  update_files:
    - ~
fabric-1.20.3:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5729136'
    }
  update_files:
    - ~
fabric-1.20.4:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	modImplementation 'curse.maven:cloth-config-348521:5729136'
    }
  update_files:
    - ~
neoforge-1.21:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729127'
    }
  update_files:
    - ~
neoforge-1.21.1:
  gradle: |
    repositories {
        maven {
            url = 'https://cursemaven.com/'
        }
    }
    dependencies {
    	implementation 'curse.maven:cloth-config-348521:5729127'
    }
  update_files:
    - ~
name: "Cloth Config API"
