forge-1.20.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:culinary-construct-296676:4818909')
    }
fabric-1.20.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4818907')
    }
quilt-1.20.1:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814122')
    }
quilt-1.20:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814122')
    }
forge-1.20.1:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:culinary-construct-296676:4814120')
    }
forge-1.20:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:culinary-construct-296676:4814120')
    }
fabric-1.20.1:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814118')
    }
fabric-1.20:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814118')
    }
quilt-1.19.4:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814112')
    }
forge-1.19.4:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:culinary-construct-296676:4814110')
    }
fabric-1.19.4:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814108')
    }
forge-1.19.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:culinary-construct-296676:4814066')
    }
forge-1.19.1:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:culinary-construct-296676:4814066')
    }
forge-1.19:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      implementation fg.deobf('curse.maven:culinary-construct-296676:4814066')
    }
fabric-1.19.2:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814064')
    }
fabric-1.19.1:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814064')
    }
fabric-1.19:
  gradle: |
    repositories {
      maven {
        url = 'https://cursemaven.com/'
      }
    }
    dependencies {
      modImplementation fg.deobf('curse.maven:culinary-construct-296676:4814064')
    }
name: "Culinary Construct"
